server:
  port: ${PORT:8888}

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qi3Solucoes/projectX-config
          clone-on-start: true

eureka:
  instance:
    preferIpAddress: true
  client:
    region: sa-east-1
    availabilityZones:
      sa-east-1: sa-east-1a,sa-east-1c
    registryFetchIntervalSeconds: 15
    eurekaServerPort: 8761
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
