server:
  port: ${PORT:8888}

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qi3Solucoes/projectX-config
          clone-on-start: true

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
